# Generated by Django 3.1.12 on 2025-05-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(choices=[('B', 'Básico'), ('I', 'Intermedio'), ('A', 'Avanzado')], max_length=1)),
                ('video_url', models.URLField()),
                ('orden', models.IntegerField(default=0)),
            ],
        ),
    ]
