# Generated by Django 3.1.12 on 2025-05-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250505_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default=12321, max_length=100),
            preserve_default=False,
        ),
    ]
