# Generated by Django 3.1.12 on 2025-05-18 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250512_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('orden', models.IntegerField(default=0)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.leccion')),
            ],
        ),
    ]
