# Generated by Django 3.1.12 on 2025-05-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='orden',
        ),
        migrations.AddField(
            model_name='video',
            name='titulo',
            field=models.CharField(default='Nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
