# Generated by Django 3.1.12 on 2025-05-19 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20250518_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='texto',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ResultadoQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.leccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
