# Generated by Django 3.1.12 on 2025-05-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoquiz',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
