# Generated by Django 3.1.12 on 2025-07-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20250719_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoquiz',
            name='total',
            field=models.IntegerField(default=30),
        ),
    ]
